# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    az login --service-principal -u 1e7c57c0-a366-47d4-b4a2-38055284cf23 -p $(clientSecret) -t 3e72f0bf-bbe4-4f6c-9553-f4fa46516343
    az ad app create --display-name testApp --native-app false --oauth2-allow-implicit-flow true --reply-urls https://test.com
